src/ChatApp/Model/Entity/User.php
<?php

namespace ChatApp\Model\Entity;

use Symfony\Component\Security\Core\User\UserInterface;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Default ORM User implementation.
 *
 * @ORM\Entity
 * @ORM\HasLifecycleCallbacks
 * @ORM\Table(name="users",
 *      indexes={
 *           @ORM\Index(columns={"username"}),
 *           @ORM\Index(columns={"name"})
 *      }
 * )
 */
class User extends Base implements UserInterface, \Serializable
{
    const ROLE_DEFAULT = 'ROLE_USER';
    const ROLE_SUPER_ADMIN = 'ROLE_SUPER_ADMIN';

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * Since some of the URLs on the site actually have the username,
     * we need to be able to map from the username to the user id.
     *
     * @ORM\Column(type="string", length=255, unique=true, nullable=true)
     */
    protected $username;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $phone_number;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $password;

    /**
     * @ORM\Column(type="array", nullable=true)
     */
    protected $roles = array();

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    protected $enabled = false;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    protected $reported = false;

    /**
     * @ORM\Column(type="string", length=6, nullable=true)
     */
    protected $captcha;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    protected $captcha_expired = false;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $captcha_expire_at;

    /**
     * @ORM\Column(type="bigint", nullable=true)
     */
    protected $facebook_uid;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $promo_code;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $endroid_gcm_id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $ios_device_id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $name;

    /**
     * @ORM\Column(type="string", length=1, nullable=true)
     */
    protected $gender;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    protected $birthday;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $ethnicity;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $region;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $interest;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    protected $aboutme;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    protected $greeting;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $photo;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $background;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    protected $latitude;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    protected $longitude;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $last_login;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $date_created;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $last_modified;

    /**
     * @ORM\OneToMany(targetEntity="Friend", mappedBy="user")
     */
    protected $friends = array();

    /**
     * @ORM\OneToMany(targetEntity="Moment", mappedBy="user")
     */
    protected $moments = array();

    /**
     * List of blocked moments.
     *
     * @ORM\ManyToMany(targetEntity="Moment")
     * @ORM\JoinTable(
     *     name="users_to_block_moments",
     *     joinColumns={@ORM\JoinColumn(name="user_id", referencedColumnName="id", onDelete="cascade")},
     *     inverseJoinColumns={@ORM\JoinColumn(name="moments_id", referencedColumnName="id", onDelete="cascade")}
     * )
     */
    protected $blockedMoments;

    /**
     * List of blocked users.
     *
     * @ORM\ManyToMany(targetEntity="User")
     * @ORM\JoinTable(
     *     name="users_to_block_users",
     *     joinColumns={@ORM\JoinColumn(name="user_id", referencedColumnName="id", onDelete="cascade")},
     *     inverseJoinColumns={@ORM\JoinColumn(name="blocked_user_id", referencedColumnName="id", onDelete="cascade")}
     * )
     */
    protected $blockedUsers;

    /**
     * Returns the unique id.
     *
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Returns a sha1() version of the unique id.
     *
     * @return mixed
     */
    public function getToken()
    {
        return sha1($this->id);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {
        return null;
    }

    /**
     * {@inheritDoc}
     */
    public function eraseCredentials()
    {
        // do nothing
    }

    /**
     * Returns the user email.
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Returns the user name.
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Returns the user birthday.
     *
     * @return \DateTime
     */
    public function getBirthday()
    {
        return $this->birthday;
    }

    /**
     * Returns the user ethnicity.
     *
     * @return string
     */
    public function getEthnicity()
    {
        return $this->ethnicity;
    }

    /**
     * Returns the user region.
     *
     * @return string
     */
    public function getRegion()
    {
        return $this->region;
    }

    /**
     * Sets the user interest.
     *
     * @param string $interest
     *
     * @return self
     */
    public function setInterest($interest)
    {
        if (is_array($interest)) {
            foreach ($interest as $key => $value) {
                if (!$value) unset($interest[$key]);
            }
            $interest = implode('|', $interest);
        }

        $this->interest = $interest;

        return $this;
    }

    /**
     * Returns the user interest.
     *
     * @return string
     */
    public function getInterest()
    {
        return $this->interest;
    }

    /**
     * Returns the user aboutme.
     *
     * @return string
     */
    public function getAboutme()
    {
        return $this->aboutme;
    }

    /**
     * Returns the user greeting.
     *
     * @return string
     */
    public function getGreeting()
    {
        return $this->greeting;
    }

    /**
     * Returns the user photo.
     *
     * @return string
     */
    public function getPhoto()
    {
        return $this->photo;
    }

    /**
     * Returns the user background.
     *
     * @return string
     */
    public function getBackground()
    {
        return $this->background;
    }

    /**
     * Set the user latitude.
     *
     * @param string $lat
     * 
     * @return self
     */
    public function setLatitude($lat)
    {
        $this->latitude = $lat;

        return $this;
    }

    /**
     * Returns the user latitude.
     *
     * @return string
     */
    public function getLatitude()
    {
        return $this->latitude;
    }

    /**
     * Set the user longitude.
     *
     * @param string $lng
     * 
     * @return self
     */
    public function setLongitude($lng)
    {
        $this->longitude = $lng;

        return $this;
    }

    /**
     * Returns the user longitude.
     *
     * @return string
     */
    public function getLongitude()
    {
        return $this->longitude;
    }

    /**
     * Sets the user gender.
     *
     * @param string $gender
     *
     * @return self
     */
    public function setGender($gender)
    {
        $this->gender = strtoupper($gender);

        return $this;
    }

    /**
     * Returns the user gender.
     *
     * @return string
     */
    public function getGender()
    {
        switch (strtolower($this->gender)) {
            case 'm': return 'Male';
            case 'f': return 'Female';
        }
        return $this->gender;
    }

    /**
     * Get friends
     *
     * @return Collection
     */
    public function getFriends()
    {
        return $this->friends ?: $this->friends = new ArrayCollection();
    }

    /**
     * Get moments
     *
     * @return Collection
     */
    public function getMoments()
    {
        return $this->moments ?: $this->moments = new ArrayCollection();
    }

    /**
     * Get blocked moments
     *
     * @return Collection
     */
    public function getBlockedMoments()
    {
        return $this->blockedMoments ?: $this->blockedMoments = new ArrayCollection();
    }

    /**
     * Get blocked users
     *
     * @return Collection
     */
    public function getBlockedUsers()
    {
        return $this->blockedUsers ?: $this->blockedUsers = new ArrayCollection();
    }

    /**
     * Never use this to check if this user has access to anything!
     *
     * Use the SecurityContext, or an implementation of AccessDecisionManager
     * instead, e.g.
     *
     *         $securityContext->isGranted('ROLE_USER');
     *
     * @param string $role
     *
     * @return Boolean
     */

templates/layout.html.twig
<!DOCTYPE html>
<html>
    <head>
        <title>ChatApp - {% block title 'Chat and meet new people' %}</title>

        <meta charset="utf-8" />
        <meta name="description" content="Be Friendly On ChatApp, Social App for your Andriod and iOS devices.">
        <meta name="keywords" content="ChatApp, Social App">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0" />

        <link rel="shortcut icon" href="{{ app.request.basepath }}/favicon.ico">

        {% block stylesheets %}
            <link href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet" />

            <link rel="stylesheet" href="{{ app.request.basepath }}/external/fontello/css/fontello.css" />
            <link rel="stylesheet" href="{{ app.request.basepath }}/external/fontello/css/animation.css" />
            <!--[if IE 7]>
                <link rel="stylesheet" href="{{ app.request.basepath }}/external/fontello/css/fontello-ie7.css" />
            <![endif]-->

            <link href="{{ app.request.basepath }}/css/style.css" rel="stylesheet" type="text/css" media="screen" />
            <link href="{{ app.request.basepath }}/css/print.css" rel="stylesheet" type="text/css" media="print" />
        {% endblock %}

        <script type="text/javascript">
        {% spaceless %}
            {% if app.user %}
                var ChatApp = {
                    baseUrl: "{{ app.request.baseUrl }}",
                    userUsername: "{{ app.user.username }}",
                    userToken: "{{ app.user.token }}"
                };
            {% endif %}
        {% endspaceless %}
        </script>

        <script type="text/javascript">
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

            ga('create', 'UA-46311862-1', 'auto');
            ga('send', 'pageview');
        </script>
    </head>
    <body class="{% if is_granted('ROLE_USER') %}loggedin{% else %}loggedout{% endif %} {{ app.request.get('_route') }} {% if errorCode is defined %}error404{% endif %}">

        {% block header %}{% endblock %}
        {% block content %}{% endblock %}

        {% block foolter %}
            <footer class="clearfix">
                <div class="content">
                    <ul>
                        <li><a href="http://guiang.com/" target="_blank">About Us</a></li>
                        <li><a href="http://guiang.com/contact" target="_blank">Contact Us</a></li>
                        <li><a href="https://testflightapp.com/join/09bd7058e7c6d2c55a38e783824f50fa-MTg0ODk5/" target="_blank">Beta Test</a></li>
                        <li><a href="https://facebook.com/TheChatApp" target="_blank" class="sprites-facebook">Facebook</a></li>
                        <li><a href="https://twitter.com/TheChatApp" target="_blank" class="sprites-twitter">Twitter</a></li>
                    </ul>
                    <p>&copy; 2014 Guiang Corporation</p>
                </div>
            </footer>
        {% endblock %}

        <a class="scroll-to-top" href="#top"><i class="icon icon-arrow-up"></i></a>

        {% block javascripts %}
            <!--[if lte IE 8]>
                <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
            <![endif]-->

            <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
            <script src="//cdnjs.cloudflare.com/ajax/libs/waypoints/2.0.3/waypoints.min.js"></script>
            <script src="//cdnjs.cloudflare.com/ajax/libs/masonry/3.1.2/masonry.pkgd.min.js"></script>
            <script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.1.1/js/bootstrap.min.js"></script>

            <script src="{{ app.request.basepath }}/js/jquery.infieldlabel.min.js"></script>
            <script src="{{ app.request.basepath }}/js/view.min.js?auto"></script>
            <script src="{{ app.request.basepath }}/js/main.js"></script>
        {% endblock %}
    </body>
</html>